apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  backend:
    serviceName: frontendsvc
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontendsvc
  labels:
    app: frontend
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/testing01-221905/testingangular05
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 80
        env:
        - name: PROJECT_ID
          value: testing01-221905
